### ISSUE TITLE
SNMPv3Set value type OctectStrings missing

### ISSUE THREAD

**Issue by AnythingOverIP** [lahell/SNMPv3#10]
Hello, 

When polling a value, i often get an OctetString value back:

```
Node         OID                                Type Value
----         ---                                ---- -----
11.11.11.11  1.3.6.1.4.1.45391.1.1.1.2.0 OctetString GA1049
```
When I try to overwrite that value, the OctetString type is not available in choices:
![image](https://github.com/lahell/SNMPv3/assets/25624251/0fc058b1-308c-4ff5-aeae-e46d1a26efc7)

Trying to push that value as string does not yield any error, but the device does not change the value (although that OID is writable). 

`$siteid = [Lextm.SharpSnmpLib.OctetString]::new('XY999')` does not do the trick either.

Am I missing something? If not, would it be possible to add the OctetString type to the list?

Thanks :)

**Comment by lahell** [comment]
`-Type String` will send the supplied value as OctetString.
https://github.com/lahell/SNMPv3/blob/master/SNMPv3/Public/Invoke-SNMPv3Set.ps1#L137-L170
