### ISSUE TITLE
Exception calling "BulkWalk" with "11" argument(s): "Request timed out after 3000-ms."

### ISSUE THREAD

**Issue by cscoengineer** [lahell/SNMPv3#6]
Exception calling "BulkWalk" with "11" argument(s): "Request timed out after 3000-ms."
At C:\Program Files\WindowsPowerShell\Modules\SNMPv3\1.1.2\Public\Invoke-SNMPv3Walk.ps1:139 
char:5
+     [Lextm.SharpSnmpLib.Messaging.Messenger]::BulkWalk(
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : TimeoutException

![image](https://user-images.githubusercontent.com/17439633/136992896-f2ce86ba-ddd5-45ed-ab89-856c2098a42a.png)

It seems to work for short invokes, but I'm doing about 100+ invoke-snmpv3walk

SHould I be placing a pause in between the invokes?

**Comment by lahell** [comment]
I'm unable to reproduce this problem. `-Timeout` defaults to 3000 ms. Have you tried to increase it? This same error message was also mentioned in issue #5.

**Comment by rgacz** [comment]
I can see similar issue:

```
PS C:\Users\Administrator> Invoke-SNMPv3Walk @walkRequest
Exception calling "BulkWalk" with "11" argument(s): "Request timed out after 5000-ms."
At C:\Program Files\WindowsPowerShell\Modules\SNMPv3\1.1.2\Public\Invoke-SNMPv3Walk.ps1:139 char:5
+     [Lextm.SharpSnmpLib.Messaging.Messenger]::BulkWalk(
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : TimeoutException

PS C:\Users\Administrator>
```

```
$walkRequest = @{
  Target     = '10.10.1.1'
  Timeout    = 5000
  UserName   = 'snmpUser'
  AuthType   = 'SHA1'
  AuthSecret = 'authKey'
  PrivType   = 'AES256'
  PrivSecret = 'privKey'
  }
```

AES256 is the reason.
A FortiGate firewall is my target.
FortiGate has two options for AES256, aes256 and aes256cisco:
```
FortiGate (snmpUser) # set priv-proto ? 
aes            CFB128-AES-128 symmetric encryption protocol.
des            CBC-DES symmetric encryption protocol.
aes256         CFB128-AES-256 symmetric encryption protocol.
aes256cisco    CFB128-AES-256 symmetric encryption protocol compatible with CISCO.
 
FortiGate (snmpUser) # set priv-proto aes256cisco
```
Invoke-SNMPv3Walk "AES256" + FortiGate "aes256" = timeout (but works with SnmpWalk.exe)
Invoke-SNMPv3Walk "AES256" + FortiGate "aes256cisco" works (but does not work with SnmpWalk.exe)

**Comment by lahell** [comment]
~~You can try to hard code different privacy providers here to find out what works for you:
https://github.com/lahell/SNMPv3/blob/master/SNMPv3/Private/Get-SNMPv3PrivacyProvider.ps1#L45-L49~~

~~You can also try to update to the latest version of BouncyCastle.Crypto.dll and SharpSnmpLib.dll in https://github.com/lahell/SNMPv3/tree/master/SNMPv3/lib.~~

@rgacz: I have updated to the latest version of SharpSnmpLib.dll. Core will now use SharpSnmpLib.dll for .NET 6 and Desktop will use SharpSnmpLib.dll for .NET Framework. Previously both Core and Desktop used SharpSnmpLib.dll for .NET Standard.

**Comment by lahell** [comment]
Closed because I cannot reproduce this issue.
