### ISSUE TITLE
Unable to use ip addresses

### ISSUE THREAD

**Issue by ghost** [lahell/SNMPv3#7]
Hi, when i want to use ip addresses instead of hostnames, i receive the message unknown host. when i use the hostname (which contains the same ip address) everything is going fine. Is this something that you can fix?

Thank you in advance!

Best regards,

Remon Willems

![Not working with IP](https://user-images.githubusercontent.com/106802859/171809612-dd857d66-2d4f-4769-8fd5-be627b22eab3.JPG)
![Working](https://user-images.githubusercontent.com/106802859/171809617-ca950a96-c415-4862-88f9-5d903a3212cd.JPG)

**Comment by lahell** [comment]
If I’m not mistaken that bug was fixed in version 1.1.1. Looks like you are using 1.1.0. You can update to the latest version with the command `Update-Module SNMPv3`.

**Comment by ghost** [comment]
Hmm, I installed it yesterday from the PSgallery. Beside that, i updated the module as you mentioned. Now running 1.1.2.
Thanks for the quick support.
Best regards,

Remon
